hassio-addons/bashio

- lib/addons.sh
Adds support for the new Hass.io API data to support Hass.io's Ingress
n/a
> ✨ Adds support for Hass.io Ingress

- lib/info.sh
> Add logging to info

- lib/bashio.sh
- lib/dns.sh
Add support for the new DNS endpoints.
n/a
> Adds support for Hass.io DNS

- lib/bashio.sh
- lib/discovery.sh
Add support for publishing and deleting discovery configurations.
n/a
> Adds support for Hass.io Discovery

- lib/addons.sh
Add support for a couple of missing add-on options./
n/a
> Adds support for new add-on options

- lib/supervisor.sh
Adds support for missing supervisor options.
n/a
> Adds support for new Supervisor options

- lib/info.sh
Adds timezone call to general info command.
n/a
> Adds support for timezone in general info command

- lib/log.sh
Adds a function to allow changing the log level on the fly
n/a
> Adds call to change log level

- lib/addons.sh
Adds 3 new properties of the Supervisor API, for add-ons, to Bashio.
- `advanced`
- `stage`
- `video`
> ✨ Adds new Supervisor add-on properties

- README.md
The semver link is broken. This PR fixes it.
> :ambulance: Fix semver link

- README.md
This PR fixes a few smaller grammar glitches in the README.
Makes it easier to read :)
> 📚 Correct a few grammar pieces in the README

- lib/net.sh
> 🚑 Fix to exit the add-on if we run into timeout

- lib/services.sh
Adds a quick method to check if a service is available.
```bash
if bashio::services.available "mqtt"; then
echo "YAY! MQTT is available!"
fi
```
> ✨ Add service available method

- lib/bashio.sh
- lib/cli.sh
- lib/os.sh
Add the new CLI features from the Supervisor API.
> ✨ Adds new CLI features

- lib/host.sh
Adds support for accessing the new host logs
> ✨ Adds support for host logs

- lib/audio.sh
- lib/bashio.sh
Adds basic support for the new audio endpoint of the Supervisor API.
> ✨ Adds basic support for audio

- lib/cache.sh
Couple of typos for log messages.
> ✏Fix typos

- lib/info.sh
> ✨ Add supported flag to supervisor info

- lib/supervisor.sh
> ✨ Add healthy / supported to supervisor

- lib/addons.sh
> ✨ Add watchdog to add-on

- lib/bashio.sh
- lib/multicast.sh
This PR adds support for controlling the Multicast plugin from Bashio.
> ✨ Add support for the Multicast API

- lib/dns.sh
Updates methods to match upstream (mainly adds new ones), for the `/dns/*` endpoints.
> 🔨 Update dns API methods

- lib/addons.sh
Updates methods to match upstream (mainly adds new ones), for the `/addons/*` endpoints.
> 🔨  Update addons API methods

- lib/core.sh
Adds support for triggering a Home Assistant Core rebuild command:
`bashio::core.rebuild()`
> Add core rebuild command

- lib/observer.sh
Add support for the Observer API endpoints exposed by the Supervisor
> Add Observer support

- lib/os.sh
Add `bashio::os.boot()` support
> Add boot property of operating system info

- lib/addons.sh
- lib/audio.sh
- lib/core.sh
- lib/dns.sh
- lib/os.sh
- lib/supervisor.sh
> Fix and improve update_available logic for all plugins

- lib/core.sh
- lib/info.sh
- lib/os.sh
Fixes a caching bug in some API endpoints where the caching key used was incorrect.
> Fix caching API response caching bug

- lib/hardware.sh
> Add usb property to hardware endpoint

- README.md
Fixes the pipelines badges for GitHub CI
> Fix pipeline badges

- lib/bashio.sh
- lib/network.sh
Allow add-ons simply to get information from Host network settings.
> Initial support for Network commands

- lib/addons.sh
> Allow to edit add-on options

- lib/bashio.sh
- lib/jq.sh
Fixes bug that calls an undefined method in jq.has_value.
fixes #74
> Fix bug to undefined method in jq.has_value

- lib/api.sh
- lib/pwned.sh
Fixes Shellcheck warning SC2295, that has been detected by a newer version of Shellcheck
> Fix shellcheck warnings

- lib/const.sh
- lib/network.sh
Both can be ignored in these cases without much issues.
../Frenck
> Adjust shellcheck warnings

- lib/info.sh
Adds access to the current running state of Core.
Needed for: <https://github.com/hassio-addons/addon-tailscale/pull/254>
> Add method to request the state of Core
