hassio-addons/bashio

lib/bashio.sh, lib/net.sh
Adds support for waiting for a TCP socket to be available. 
Useful for e.g., waiting for a subservice to be available/started, before starting NGinx.
```bash
bashio::net.wait_for 8080
exec nginx
```
n/a
=> ✨Adds waiting for TCP port support

lib/addons.sh
Adds support for fetching specific port configuration and their descriptions.
n/a
=> ✨ Adds support for fetching ports and port descriptions

lib/bashio.sh, lib/services.sh
=> Adds support for services

lib/addons.sh, lib/core.sh, lib/dns.sh, lib/os.sh, lib/supervisor.sh
Everything `last_version` was renamed to `version_latest` in the latest Supervisor API.
=> 🔨 last_version -> version_latest

lib/info.sh
Add support for:
- `bashio::info.docker()`
- `bashio::info.operating_system()`
This will improve the startup time for add-ons in the community add-ons, and allows for the removal of API access for some add-ons.
=> Add Docker & Operating System info properties

lib/cli.sh, lib/core.sh
`bashio::core.update_available` & `bashio::cli.update_available` implemented their own logic to determine if there was an update available.
However, nowadays, that is just a property. So, just using that.
=> Replace update available logic with property access

lib/host.sh
Adds three new properties to the host endpoint:
- `bashio::host.disk_used`
- `bashio::host.disk_total`
- `bashio::host.disk_free`
=> Add disk stats to host endpoint

LICENSE.md, README.md
Happy New Year
This PR updates the maintenance and license years.
Furthermore replaces the GitLab CI badge with a GitHub Actions version.
=> Update license and documentation

lib/addons.sh
Fixes an unbound variable occurrence in `bashio::addon.update_available`.
Causes: `/usr/lib/bashio/addons.sh: line 443: slug: unbound variable`
=> Fix slug: unbound variable in addon.update_available

lib/const.sh
The platform started to using one shared shm to simplify the eco system. To make the cache only available for himself, we need to use the system tmp.
=> Using new cache location

lib/const.sh
```
@Frenck I have tested bashio. My only mind would be if we not want use a dot
/tmp/.bashio/
instead of /tmp/bashio
```
Agreed.
=> Put Bashio cache folder in a dot folder inside tmp

lib/config.sh
=> 📚 Minor typos

lib/hardware.sh
This PR removes the method `bashio::hardware.trigger()`.
It uses the now deprecated `/hardware/trigger`, thus the method is removed.
=> Remove deprecated hardware trigger method

lib/addons.sh
Updates the add-on options to match Supervisor 2021.2.
Breaking change: `auto_uart` was removed and replaced by `uart`.
Additionally, `usb` is added to the Bashio API.
=> Add new add-on options from Supervisor 2021.2

lib/config.sh
So we can do stuff like:
```bash
non_existing_config=$(bashio::config.get("non-existing", "default value")
```
=> Allow fetching configuration parameters with a default value

lib/config.sh
0.14.0, introduced the possibility to pass a default value to the config options, in order to get a different default value returned if an option wasn't set by the user.
However, the default of the default value, was an empty string. This caused not set configuration options to become set...
This PR fixes that behavior by making the default value `null`, which is the same as not set.
It also saves a couple of calls this way :)
Tested with the Z-Wave JS @ MQTT add-on, which relies on this.
=> Fix default value handling for configuration options

lib/addons.sh
Bashio handles `{}` as an empty value. This works nicely when working with Bash, as it doesn't handle dictionaries that well.
In the case of fetching the full configuration from the Supervisor API, this may lead to a surprising issue. If there is no add-on configuration, it returns `{}` is handled as empty by Bashio.
When later processing values from the empty config, `jq` simply returns empty results 🤷 
To prevent these issues, I've added a small check to ensure we return an empty JSON object when there is no add-on configuration.
This makes Bashio behave exactly the same as with the previous `options.json` method.
=> Fix processing of empty add-on config

lib/var.sh
- Allow new lines to be used in values for the `var.json`
- Properly escape all characters for a proper JSON string, not only line breaks
- Fix issue when `^` character would be used in a key and the key would evaluated as `key` rather than `"^key"` leading to a non-valid JSON
- Introduces a function `var.json_string` which escapes a Bash string for use in a JSON object
Fixes #94
=> Allow multiple lines in var.json

lib/api.sh
When trying to develop an addon, I got messages like this appearing in the logs of the addon:
```
parse error: Expected string key before ':' at line 1, column 4
```
When all I was doing was:
```
HOST=$(bashio::host)
```
It turned out this was caused by a jq statement trying to parse the string
```
403: Forbidden
```
By adding this extra error message, we give developers a bit more of a hint as to what is wrong.
=> Add error message for 403 error on API access

lib/info.sh
Typo introduced in #142 (code is OK, only the comment is misleading)
=> Fix comment/docs typo in info.state

lib/log.sh
Improper quoting causes the replacement string in the log format to be mangled. Specifically, instances of `&` in a log message will be replaced with the replacement pattern in the log format (namely: `{MESSAGE}`).
For example:
```sh
bashio::log.info "FOO&BAR&BAZ"
```
produces:
```
[08:17:56] INFO: FOO{MESSAGE}BAR{MESSAGE}BAZ
```
although one would expect it to produce:
```
[08:17:56] INFO: FOO&BAR&BAZ
```
This PR quotes the replacement strings so that the `&` character is treated as a literal character by bash.
---
From [the bash manual](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion):
> If the `patsub_replacement` shell option is enabled using `shopt`, any unquoted instances of ‘&’ in *string* are replaced with the matching portion of *pattern*. This is …
=> Properly quote replacment string in param expansion

lib/bashio
Quality of life improvement for handling arguments, mostly useful for testing things on the command line.
Shifts around the arguments (and sets argv[0] to the target script) so that they would be as you expect if the call at the end of `bashio` was `exec "$@"` instead of `source "$@"`.
From the [bash manual](https://www.gnu.org/software/bash/manual/bash.html#Bourne-Shell-Builtins):
> If any `arguments` are supplied, they become the positional parameters when `filename` is executed. Otherwise the positional parameters are unchanged.
This makes handling arguments annoying, because there's no way other than testing `[[ $1 = $EXPECTED_SCRIPT_PATH ]]` to see if arguments were passed on the command line. And if arguments are passed, there's no way to access the true script's path
given …
=> Fix arguments for sourced script

lib/api.sh
No reason this should fail, AFAICT. In fact, it makes it hard to detect if there are any HTTP errors.
=> Fix exit code when calling supervisor api with raw=true

lib/var.sh
Fix minor typos in documentation
There are none
=> Fix typo in var.true() and var.false() documentation
